version: 2.1
orbs: 
  codecov: codecov/codecov@3.2.2
jobs:
 build:  
   machine: true
   steps:
     - checkout
     
     # run test postgres
     - run: docker run --rm -e POSTGRES_PASSWORD=test -p 5432:5432 -d postgres:12-alpine  
     
     # build the application image
     - run: docker build . -t test-docker --build-arg DOCKER_TYPE=TEST 
      
     # run test app
     - run: docker run -it --rm --network=host -v ${PWD}/coverage:/mnt/coverage test-docker bash /usr/local/libasyik/tests/test_and_coverage.sh

     - codecov/upload:
         file: coverage/libasyik_test.info

